---
title: "cleaning final project"
author: "Malek Alsoubani"
date: "2022-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(httr)
library(XML)
library(readxl)
library(fastDummies)
library(pedometrics)
library(caret)
library(car)
library(janitor)
library(MASS)
library(ggfortify)
library(olsrr)
library(ggplot2)
library(Metrics)
library(gghighlight)
library(readr)
address1="C:/Users/14035/OneDrive - University of Calgary/Desktop/BTMA 431/15000pg_kijiji_data_fullset_dodge__ford__gmc__hyundai__jeep__ram__toyota.csv"
rawdatadf=read.csv(address1)
address2="C:/Users/14035/OneDrive - University of Calgary/Desktop/BTMA 431/Cities and zones.xlsx"
Cityzonedf=read.csv(address2)
```

```{r}
#collect cities
url <- "https://en.wikipedia.org/wiki/List_of_cities_in_Alberta"
getObject <- GET(url) 
commsParsed <- htmlParse(getObject)
pageTables <- readHTMLTable(commsParsed, stringsAsFactors = FALSE, header = T)

pageTables=pageTables[[1]]

pageTables=pageTables[-1,1]
pageTables=pageTables[-20]
pageTables=gsub("\\[.*", "", pageTables)
pageTables=gsub("\\(.*", "", pageTables)
cities=c(pageTables)
#collect towns
url <- "https://en.wikipedia.org/wiki/List_of_towns_in_Alberta"
getObject <- GET(url) 
commsParsed <- htmlParse(getObject)
pageTables <- readHTMLTable(commsParsed, stringsAsFactors = FALSE, header = T)

pageTables=pageTables[[1]]

pageTables=pageTables[-1,1]

pageTables=pageTables[-106]
pageTables=gsub("\\[.*", "", pageTables)
cities=c(cities,pageTables,"Sherwood Park",'calgary',"Fort McMurray","Lloydminster",'Acme','Nisku',"Alberta Beach","De Winton",'Lomond',"Barnwell")

```

```{r}
#Duplicated data from either the collecting process or the Kijiji website itself.
rawdatadf=rawdatadf %>%
  distinct()
#The brand, wheel configuration, price, model, colour, condition, or fuel type of the car being left empty.
rawdatadf=rawdatadf %>%
  filter(brand!='')

rawdatadf=rawdatadf %>%
  filter(wheel_config!='')

rawdatadf=rawdatadf %>%

  filter(list_price!=0)
#The Model being left as “other”.
rawdatadf=rawdatadf %>%
  filter(model!='Other')

rawdatadf=rawdatadf %>%
  filter(model!='')

rawdatadf=rawdatadf %>%
  filter(color!='')
rawdatadf=rawdatadf %>%
  filter(fuel_type!='')
# Transmission of the car being left as empty, “0”, or “other”
rawdatadf$fuel_type[rawdatadf$fuel_type=="Other"] <- "Gasoline"
rawdatadf$transmission[rawdatadf$transmission==""] <- "Automatic"
rawdatadf$transmission[rawdatadf$transmission=="0"] <- "Automatic"
rawdatadf$transmission[rawdatadf$transmission=="Other"] <- "Automatic"
#Changing the Carfax Link to “yes” or “no”, the link itself is not useful for our data modeling.
rawdatadf$carfax_link=ifelse(rawdatadf$carfax_link!="","Yes","No")
#Changing the columns to either factors, numerical variables or character variables
rawdatadf$brand=as.factor(rawdatadf$brand)
rawdatadf$model=as.factor(rawdatadf$model)
rawdatadf$list_price=as.numeric(rawdatadf$list_price)
rawdatadf$model_year=as.numeric(rawdatadf$model_year)
rawdatadf$color=as.factor(rawdatadf$color)
rawdatadf$configration=as.character(rawdatadf$configration)

#Find the city/ town/village in dealer address column.
for(i in cities){
  counter=0
  for(j in rawdatadf$dealer_address){
    counter=counter+1
    test=grepl(i,j)
    if (test==TRUE){
      rawdatadf$dealer_address[counter]=i
      }
  }
}

rawdatadf$city=rawdatadf$dealer_address
rawdatadf$city=as.factor(rawdatadf$city)

rawdatadf=rawdatadf %>%
  filter(condition!='')
rawdatadf$carfax_link=as.factor(rawdatadf$carfax_link)
rawdatadf$fuel_type=as.factor(rawdatadf$fuel_type)
rawdatadf$body_type[rawdatadf$body_type=="Other"] <- "Pickup Truck"
rawdatadf$body_type=as.factor(rawdatadf$body_type)
#Wheel Configurationof the car being left as empty or “other”.
rawdatadf$wheel_config[rawdatadf$wheel_config==""] <- "4x4"
rawdatadf$wheel_config[rawdatadf$wheel_config=="Other"] <- "4x4"
rawdatadf$wheel_config=as.factor(rawdatadf$wheel_config)
rawdatadf$condition=as.factor(rawdatadf$condition)
rawdatadf$mileage=as.numeric(rawdatadf$mileage)
#Configuration was extremely dirty lots of random elements.
cleandatadf=data.frame(brand=rawdatadf$brand,model=rawdatadf$model,model_year=rawdatadf$model_year,list_price=rawdatadf$list_price,color=rawdatadf$color,condition=rawdatadf$condition,body_type=rawdatadf$body_type,wheel_config=rawdatadf$wheel_config,transmission=rawdatadf$transmission,fuel_type=rawdatadf$fuel_type,mileage=rawdatadf$mileage,carfax_link=rawdatadf$carfax_link,city=rawdatadf$city)
vehicle_data=cleandatadf

```

```{r}

#Changing the cities/towns/ villages into 5 separate sections of Alberta (Edmonton Zone, Calgary Zone, Central Zone, North Zone, South Zone)
regions_clean_data=cleandatadf


Cityzonedf$`City or Town`=str_trim(Cityzonedf$`City or Town`, side = c("both", "left", "right"))
Cityzonedf$`City or Town`=str_squish(Cityzonedf$`City or Town`)
na.omit(Cityzonedf$`City or Town`)
regions_clean_data$city=str_trim(regions_clean_data$city, side = c("both", "left", "right"))
regions_clean_data$city=str_squish(regions_clean_data$city)

counter1=0
for(i in Cityzonedf$`City or Town`){
  counter1=counter1+1
  regions_clean_data$city[regions_clean_data$city==i] <- Cityzonedf$Zone[counter1]
}

regions_clean_data$city=gsub("Fort McMurray","Edmonton Zone ",regions_clean_data$city)
regions_clean_data$city=gsub("Sherwood Park","Calgary Zone ",regions_clean_data$city)
regions_clean_data$city=gsub("calgary","Calgary Zone ",regions_clean_data$city)
regions_clean_data$city=gsub("Ponoka","Central Zone ",regions_clean_data$city)
regions_clean_data$city=gsub("Nisku","North Zone ",regions_clean_data$city)
regions_clean_data$city=gsub("De Winton","North Zone ",regions_clean_data$city)
regions_clean_data$city=str_trim(regions_clean_data$city, side = c("both", "left", "right"))
regions_clean_data$city=str_squish(regions_clean_data$city)
regions_clean_data$city=as.factor(regions_clean_data$city)

clean_with_region=write.csv(regions_clean_data, "C:/Users/14035/OneDrive - University of Calgary/Desktop/BTMA 431/cleandatakijiji_with_zones.csv", row.names=FALSE)

```

```{r}
## CREATION OF REGRESSION MODEL ##
# CREATING DUMMY VARIABLES
vehicle_data_dummy <- dummy_cols(vehicle_data, select_columns = c('brand','model','color','condition','body_type','wheel_config','transmission','fuel_type','carfax_link','city'))
vehicle_data_dummy <- dummy_cols(vehicle_data, select_columns = c('brand','model','color','condition','body_type','wheel_config','transmission','fuel_type','carfax_link','city'), remove_selected_columns = TRUE)


# REMOVING HIGHLY CORRELATED VALUES
vehicle_data_cor = cor(vehicle_data_dummy)
hc = findCorrelation(vehicle_data_cor, cutoff = 0.95)
hc = sort(hc)
vehicle_data_no_cor = vehicle_data_dummy[,-c(hc)]


# RUNNING FIRST REGRESSION
price_model_0 <- lm(log(vehicle_data_no_cor$list_price) ~ ., data = vehicle_data_no_cor) 
summary(price_model_0)


# REMOVING 'NA' VALUES FROM REGRESSION
drops <- c("brand_Toyota","model_Transit Connect","model_VENUE","model_Viper","model_Wrangler","model_Yaris","model_Yukon","color_Yellow","body_type_Wagon",
           "wheel_config_Rear-wheel drive (RWD)","fuel_type_Hybrid-Electric","city_Black Diamond","city_Whitecourt")
vehicle_data_no_NA <- vehicle_data_no_cor[ , !(names(vehicle_data_no_cor) %in% drops)]
vehicle_data_no_NA <- clean_names(vehicle_data_no_NA)
```

```{r}

# RUNNING SECOND REGRESSION
price_model_1 <- lm(log(vehicle_data_no_NA$list_price) ~ ., data = vehicle_data_no_NA) 
summary(price_model_1)


# USING STEP VIF TO REMOVE MULTICOLLINEARITY 
price_model.stepVIF <- stepVIF(price_model_1, threshold = 5, verbose = TRUE) 
summary(price_model.stepVIF)


# USING STEPWISE 'BOTH' TO CHOOSE BEST PREDICTORS BASED ON P-VALUE
stepwise_both_pval <- ols_step_both_p(price_model.stepVIF)

keeps_both <- stepwise_both_pval$predictors
keeps_both <- append(keeps_both, "list_price")
data_both_pval <- subset(vehicle_data_no_NA, select = keeps_both)

```
```{r}
# RUNNING THIRD REGRESSION
price_model_both_pval <- lm(log(data_both_pval$list_price) ~ ., data = data_both_pval) 
summary(price_model_both_pval)


# ROOT MEAN SQUARED ERROR AND AVERAGE ABSOLUTE ERROR
model_RMSE <- sqrt(mean(price_model_both_pval$residuals^2))
model_RMSE

model_MAE <-mae(data_both_pval$list_price, exp(predict(price_model_both_pval)))
model_MAE

## Regression Formula
cc <- price_model_both_pval$coefficients
(eqn <- paste("Y =", paste(round(cc[1],5), paste(round(cc[-1],5), names(cc[-1]), sep=" * ", collapse=" + "), sep=" + "), "+ e"))
(eqn <- gsub('\\+ -', '- ', gsub(' \\* ', '*', eqn)))

Y = exp(-97.98612 + 0.05402*model_year - 0.33668*wheel_config_front_wheel_drive_fwd + 0*mileage - 0.29492*fuel_type_gasoline + 0.07181*body_type_pickup_truck - 
  1.13095*model_caliber - 0.32289*model_escape - 0.21352*body_type_sedan + 0.30941*model_expedition + 0.89117*model_power_ram_3500 + 0.66828*model_f_150_raptor + 
  1.07757*model_excursion + 0.27642*model_3500 + 0.23052*model_f_350 + 0.28941*model_sienna + 0.39863*model_transit + 0.39389*model_wagoneer + 
  0.23407*model_challenger - 0.27136*model_ranger - 0.59922*model_patriot - 0.35847*model_journey - 0.47506*model_power_ram_1500 + 0.08881*brand_dodge + 
  0.14666*model_4runner + 0.29988*model_sierra_2500 + 0.27795*model_sierra_3500 - 0.42705*model_eco_sport + 0.08915*wheel_config_4_x_4 - 0.2607*model_cherokee - 
  0.35603*model_compass - 1.29333*model_liberty - 0.82227*city_strathmore + 0.27802*city_stettler - 0.22991*model_focus - 0.84457*color_beige - 
  0.39844*model_explorer_sport - 0.21046*model_tucson - 0.20572*model_santa_fe - 0.21869*model_terrain - 0.42986*model_flex - 0.12126*model_edge - 
  0.63095*model_matrix + 0.2604*model_camry - 0.71914*condition_lease_takeover - 0.17807*model_acadia - 0.15073*model_rav4 + 0.08923*city_airdrie - 
  0.55813*city_legal - 0.18184*city_stony_plain - 0.05803*model_f_150 + 0.24933*city_westlock - 0.58429*model_dakota + 0.03877*city_edmonton - 0.05042*color_blue + 
  0.51198*city_peace_river + 0.4857*model_venza - 0.2434*model_fiesta + 0.61617*city_coronation + 0.45466*model_f_450 + 0.43663*city_provost + 0.15339*model_sonata + 
  0.15289*model_gt - 0.31312*city_calgary + 0.21423*model_bronco_ii + 0.11593*city_bonnyville + 0.06727*transmission_manual + 0.17073*model_savana + 
  0.15983*model_palisade + 0.18894*city_camrose + 0.3684*model_c_k_2500 + 0.3691*city_sundre)
```

```{r}
## Example Car: 2016 Toyota Rav4, 130,000km
predicted_price_RAV4 <- exp(-97.9861 + 0.054*(2016) - 0.3367*(0) + 0*(130000) - 0.2949*(1) + 0.0718*(0) - 
                        1.131*(0) - 0.3229*(0) - 0.2135*(0) + 0.3094*(0) + 0.8912*(0) + 0.6683*(0) + 
                        1.0776*(0) + 0.2764*(0) + 0.2305*(0) + 0.2894*(0) + 0.3986*(0) + 0.3939*(0) + 0.2341*(0) - 
                        0.2714*(0) - 0.5992*(0) - 0.3585*(0) - 0.4751*(0) + 0.0888*(0) + 0.1467*(0) + 
                        0.2999*(0) + 0.278*(0) - 0.427*(0) + 0.0891*(0) - 0.2607*(0) - 0.356*(0) - 
                        1.2933*(0) - 0.8223*(0) + 0.278*(0) - 0.2299*(0) - 0.8446*(0) - 0.3984*(0) - 0.2105*(0) - 
                        0.2057*(0) - 0.2187*(0) - 0.4299*(0) - 0.1213*(0) - 0.6309*(0) + 0.2604*(0) - 0.7191*(0) - 
                        0.1781*(0) - 0.1507*(1) + 0.0892*(0) - 0.5581*(0) - 0.1818*(0) - 0.058*(0) + 0.2493*(0) - 
                        0.5843*(0) + 0.0388*(0) - 0.0504*(0) + 0.512*(0) + 0.4857*(0) - 0.2434*(0) + 0.6162*(0) + 
                        0.4547*(0) + 0.4366*(0) + 0.1534*(0) + 0.1529*(0) - 0.3131*(1) + 0.2142*(0) + 0.1159*(0) + 
                        0.0673*(0) + 0.1707*(0) + 0.1598*(0) + 0.1889*(0) + 0.3684*(0) + 0.3691*(0))
predicted_price_RAV4

```

```{r}
# DATAFRAME SHOWING PREDICTIONS VS ACTUAL
plot_data <- data.frame(Predicted_value = exp(predict(price_model_both_pval)),  Observed_value = data_both_pval$list_price)
ggplot(plot_data, aes(x = Predicted_value, y = Observed_value)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "green")

vehicle_data_w_pred <- vehicle_data
vehicle_data_w_pred$prediction <- plot_data$Predicted_value
```

```{r}


## OUTLIERS SELECTION AND EXPLINATION ##

cooksd <- as.vector(unlist(cooks.distance(price_model_both_pval)))
cooksd_df <- data.frame(c(1 : 1409), cooksd)
colnames(cooksd_df)[1] = "Index"

ggplot(cooksd_df, aes(x = Index, y = cooksd)) +
  geom_point() +
  ggtitle("Influential Outliers by Cooks distance") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  geom_hline(yintercept = 0.03, linetype = "dashed", color = "red") + 
  gghighlight(cooksd > 0.03,  label_key = Index)


outlier_index <- as.vector(unlist(which(cooksd > 0.03)))
outlier_df <- vehicle_data_w_pred[outlier_index,]
outlier_df$outlier_link <- c("https://www.kijiji.ca/v-cars-trucks/grande-prairie/2013-denali-diesel-for-sale-or-trade/1642644364",
                             "https://www.kijiji.ca/v-cars-trucks/edmonton/2014-gmc-sierra-3500hd-diesel-flat-deck-191km-needs-engine/1642934964",
                             "https://www.kijiji.ca/v-cars-trucks/calgary/2018-dodge-challenger-srt-demon-no-fees/m3987611",
                             "https://www.kijiji.ca/v-cars-trucks/calgary/1966-ford-mustang-coupe/1642979269",
                             "NULL",
                             "NULL",
                             "https://www.kijijiautos.ca/cars/dodge/viper/used/#vip=21957551")
outlier_df$outlier_reason <- c("Massively overpriced",
                               "Engine blown",
                               "Intangible value not captured",
                               "Intangible value not captured",
                               "Unsure",
                               "Likely mileage is stated wrong",
                               "Intangible value not captured")
outlier_df <- outlier_df[, c(1, 2, 3, 4, 14, 16, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15)]

```

```{r}


kijiji_data <- cleandatadf

#Difference in prices for different brand models
################################################
################################################
kijiji_ford = kijiji_data %>% 
  filter(brand=="Ford")
modelregression_ford <- lm(list_price ~ model + model_year, data = kijiji_ford)
summary(modelregression_ford)
#Residual standard error: 14230 on 391 degrees of freedom
#Multiple R-squared:  0.6923,	Adjusted R-squared:  0.6718 
#F-statistic: 33.83 on 26 and 391 DF,  p-value: < 2.2e-16

kijiji_ram = kijiji_data %>% 
  filter(brand=="Ram")
modelregression_ram <- lm(list_price ~ model + model_year, data = kijiji_ram)
summary(modelregression_ram)
#Residual standard error: 11860 on 339 degrees of freedom
#Multiple R-squared:  0.6998,	Adjusted R-squared:  0.6963 
#F-statistic: 197.6 on 4 and 339 DF,  p-value: < 2.2e-16

kijiji_toyota = kijiji_data %>% 
  filter(brand=="Toyota")
modelregression_toyota <- lm(list_price ~ model + model_year, data = kijiji_toyota)
summary(modelregression_toyota)
#Residual standard error: 7218 on 87 degrees of freedom
#Multiple R-squared:  0.7954,	Adjusted R-squared:  0.7648 
#F-statistic: 26.02 on 13 and 87 DF,  p-value: < 2.2e-16

kijiji_gmc = kijiji_data %>% 
  filter(brand=="GMC")
modelregression_gmc <- lm(list_price ~ model + model_year, data = kijiji_gmc)
summary(modelregression_gmc)
#Residual standard error: 10700 on 126 degrees of freedom
#Multiple R-squared:  0.7641,	Adjusted R-squared:  0.7472 
#F-statistic: 45.34 on 9 and 126 DF,  p-value: < 2.2e-16

kijiji_jeep = kijiji_data %>% 
  filter(brand=="Jeep")
modelregression_jeep <- lm(list_price ~ model + model_year, data = kijiji_jeep)
summary(modelregression_jeep)
#Residual standard error: 10200 on 174 degrees of freedom
#Multiple R-squared:  0.7536,	Adjusted R-squared:  0.7423 
#F-statistic: 66.53 on 8 and 174 DF,  p-value: < 2.2e-16

kijiji_hyundai = kijiji_data %>% 
  filter(brand=="Hyundai")
modelregression_hyundai <- lm(list_price ~ model + model_year, data = kijiji_hyundai)
summary(modelregression_hyundai)
#Residual standard error: 3805 on 90 degrees of freedom
#Multiple R-squared:  0.8597,	Adjusted R-squared:  0.8456 
#F-statistic: 61.26 on 9 and 90 DF,  p-value: < 2.2e-16

kijiji_dodge = kijiji_data %>% 
  filter(brand=="Dodge")
modelregression_dodge <- lm(list_price ~ model + model_year, data = kijiji_dodge)
summary(modelregression_dodge)
#Residual standard error: 16530 on 114 degrees of freedom
#Multiple R-squared:  0.5661,	Adjusted R-squared:  0.5204 
#F-statistic: 12.39 on 12 and 114 DF,  p-value: 8.645e-16

```

```{r}

#Model year and mileage
#######################
#######################
mileageregression_ford <- lm(list_price ~ mileage + model_year, data = kijiji_ford)
summary(mileageregression_ford)
#Residual standard error: 18400 on 415 degrees of freedom
#Multiple R-squared:  0.4538,	Adjusted R-squared:  0.4512 
#F-statistic: 172.4 on 2 and 415 DF,  p-value: < 2.2e-16

mileageregression_ram <- lm(list_price ~ mileage + model_year, data = kijiji_ram)
summary(mileageregression_ram)
#Residual standard error: 14600 on 341 degrees of freedom
#Multiple R-squared:  0.5424,	Adjusted R-squared:  0.5397 
#F-statistic: 202.1 on 2 and 341 DF,  p-value: < 2.2e-16

mileageregression_toyota <- lm(list_price ~ mileage + model_year, data = kijiji_toyota)
summary(mileageregression_toyota)
#Residual standard error: 10240 on 98 degrees of freedom
#Multiple R-squared:  0.5362,	Adjusted R-squared:  0.5267 
#F-statistic: 56.65 on 2 and 98 DF,  p-value: < 2.2e-16

mileageregression_gmc <- lm(list_price ~ mileage + model_year, data = kijiji_gmc)
summary(mileageregression_gmc)
#Residual standard error: 15820 on 133 degrees of freedom
#Multiple R-squared:  0.4556,	Adjusted R-squared:  0.4475 
#F-statistic: 55.66 on 2 and 133 DF,  p-value: < 2.2e-16

mileageregression_jeep <- lm(list_price ~ mileage + model_year, data = kijiji_jeep)
summary(mileageregression_jeep)
#Residual standard error: 12870 on 180 degrees of freedom
#Multiple R-squared:  0.5936,	Adjusted R-squared:  0.5891 
#F-statistic: 131.5 on 2 and 180 DF,  p-value: < 2.2e-16

mileageregression_hyundai <- lm(list_price ~ mileage + model_year, data = kijiji_hyundai)
summary(mileageregression_hyundai)
#Residual standard error: 6858 on 97 degrees of freedom
#Multiple R-squared:  0.5085,	Adjusted R-squared:  0.4984 
#F-statistic: 50.18 on 2 and 97 DF,  p-value: 1.09e-15

mileageregression_dodge <- lm(list_price ~ mileage + model_year, data = kijiji_dodge)
summary(mileageregression_dodge)
#Residual standard error: 18130 on 124 degrees of freedom
#Multiple R-squared:  0.4317,	Adjusted R-squared:  0.4225 
#F-statistic:  47.1 on 2 and 124 DF,  p-value: 6.068e-16

```



